apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: client-cert
  namespace: istio-system
spec:
  secretName: client-tls-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - erp.client.com.do
