apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-system
spec:
  secretName: odoo-tls-cert
  keyAlgorithm: ecdsa
  keySize: 256
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: gdgsd19.do
  dnsNames:
    - gdgsd19.do
    - "*.gdgsd19.do"
